### ISSUE TITLE
Use as Symfony service

### ISSUE THREAD

**Issue by genietto84** [doctrine/orientdb-odm#189]
Hi,
I look about tutorial http://odino.org/starting-to-play-with-the-doctrine-orientdb-odm/ and previous iusses https://github.com/doctrine/orientdb-odm/issues/177

I've problem with this portion of configuration
odm.mapper:
    class: Doctrine\ODM\OrientDB\Mapper
    arguments:
      documentProxyDirectory: %orientdb_proxy_dir%
      annotationReader: @odm.annotationreader
    calls:
      - [setDocumentDirectories, [ %orientdb_domain_dir% : %orientdb_domain_namespace% ] ]

The latest version of odm have not Mapper Class. What's new Service configuration
Tnx

**Comment by Garani71** [comment]
I have the same issue: there is a name space as such, but not the class.

**Comment by odino** [comment]
I think that's quite an old article, and @mitom changed the implementation of how we map stuff in [this pr](https://github.com/doctrine/orientdb-odm/pull/184)...hope it helps :) @mitom do you have an example configuration for the guys?

**Comment by odino** [comment]
Also, if you guys dont mind and wanna play around with it you can use the [beta 7](https://github.com/doctrine/orientdb-odm/tree/1.0.0-beta7) which still relies on the old API

**Comment by Garani71** [comment]
Ok, let me get this straight...

- Old Beta 7 are symfony compliant, other then having to write a service.
- Master in not symfony compliant.

Other then the refactoring and proxies, Beta7 and Master are pretty much the same?

Well, that and the fact that beta 7 downgrades doctrine to 2.3.x and symfony to 2.6.1, and the symfony cache goes berserk because cannot flush when downgrading.

**Comment by mitom** [comment]
The new configuration is at the moment quite ugly I'd say (I still think it's better than before, but the refactoring I started is incomplete and halted due to a bug). Oh and there is no such thing as symfony compliant.
As for an example for symfony:

````yml
odb.binding_paramters:
    class: Doctrine\OrientDB\Binding\BindingParameters
    arguments: ["host", "port", "username", "password", "database"]

odm.binding:
    class: Doctrine\OrientDB\Binding\HttpBinding
    arguments: ["@odb.binding_parameters"]

odm.configuration:
    class: Doctrine\ODM\OrientDB\Configuration
    arguments: [{
        "document_dirs": ["dir1", "dir2"],
        "proxy_dir": "path/to/dir"
    }]

odm.manager:
    class: Doctrine\ODM\OrientDB\Manager
    arguments: ["@odm.binding", "@odm.configuration"]
````

I don't have a symfony installation handy to test it though. A few extra notes:
* This could be much shorter in definition, if instead of 4 services there would be a factory, to which all the options are passed and it returns a Manager.
* Check Doctrine\ODM\OrientDB\Configuration to see how to pass the arguments.
* In case you need serialization (which is likely if you wanna use this for users) you will need to autoload your entity classes. This is usually taken care of in the bundle for these components, but since there's no bundle for this yet, you have to do it on your own. Take a look at the mongodb one to see how it's done.
