### ISSUE TITLE
Fatal error: Class 'Doctrine\ODM\OrientDB\Mapper' not found

### ISSUE THREAD

**Issue by flik** [doctrine/orientdb-odm#191]
When I run menu.php example this error is coming

Fatal error: Class 'Doctrine\ODM\OrientDB\Mapper' not found

**Comment by odino** [comment]
hey @flik would you have any other info? PHP version, etc? It might be that those examples are a bit outdated :-P

**Comment by flik** [comment]
PHP 5.5.20-1+ 
I downloaded the latest version and I am using ubuntu OS

**Comment by bazo** [comment]
the examples are totally outdated. class Mapper doesn't even exist. it's a namespace. shat should we use instead?

**Comment by flik** [comment]
I am finding another way. Give me little time...

**Comment by flik** [comment]
https://github.com/AntonTerekhov/OrientDB-PHP
Check now

**Comment by flik** [comment]
@bazo https://github.com/AntonTerekhov/OrientDB-PHP

**Comment by yoh** [comment]
Hi @flik , here is my service definition (used in sf2 project) inspired by the example :
````
services:
    orientdb.binding.parameters:
        class: Doctrine\OrientDB\Binding\BindingParameters
        arguments:
            host:     127.0.0.1
            port:     2480
            username: %database_username%
            password: %database_password%
            database: %database_name%
    orientdb.binding:
        class: Doctrine\OrientDB\Binding\HttpBinding
        arguments:
            parameters: @orientdb.binding.parameters
    orientdb.configuration:
        class: Doctrine\ODM\OrientDB\Configuration
        arguments:
            - proxy_dir: %base-dir%/tmp
    odm:
        class: Doctrine\ODM\OrientDB\Manager
        arguments:
            binding: @orientdb.binding
            configuration: @orientdb.configuration

parameters:
    base-dir: %kernel.root_dir%/..
````

I'm now able to do this (after create database and schema with studio) : 
````
        $manager = $this->get('odm');
        $pageRepository = $manager->getRepository('Domain\Model\Page');
        $pages = $pageRepository->findAll();
````

I hope this helps you ! :)

PS : I just see that this is an old issue...
